# Name of your site (displayed in the header)
name: Reading note of Hendrix

# Short bio or description (displayed in the header)
description: Industrial Policy analyst, Data Analyst

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
(아래는 주요 링크입니다.)
footer-links:
  dribbble:
  email: flyinghendrix@gmail.com
  facebook:
  flickr:
  github: harryyang1982
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: flyhendrixfly_
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


(구글 analytics 를 통해 트래킹을 원하면 코드만 적으면 됩니다.)
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics:
